Auth/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

NewsApp/urls.py
# newsapp/urls.py
from django.urls import path
from django.conf.urls.static import static

from NewsProject import settings
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('account/', views.account, name='account'),
    path('analytics/', views.analytics, name='analytics'),
    path('lists/', views.lists, name='lists'),
    path('add_news/', views.add_news, name='add_news'),
    path('add_manager/', views.add_manager, name='add_manager'),  # Новый URL для добавления менеджера
    path('change_news_status/', views.change_news_status, name='change_news_status'),
    path('banks/update_manager/<int:bank_id>/', views.update_bank_manager, name='update_bank_manager'),
    path('banks/create/', views.create_bank, name='create_bank'),
    path('remove_bank/<int:bank_id>/', views.remove_bank, name='remove_bank'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NewsProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('Auth.urls')),
    path('', include('NewsApp.urls')),
]

NewsApp/models.py
from django.contrib.auth.models import User
from django.db import models

class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    banks_managed = models.ManyToManyField('Bank', related_name='managers')

    def __str__(self):
        return self.user.username

class Bank(models.Model):
    name = models.CharField(max_length=255)
    ceo = models.CharField(max_length=255)
    manager = models.ForeignKey(Manager, on_delete=models.SET_NULL, null=True, blank=True, related_name='managed_banks')

    def __str__(self):
        return self.name

class News(models.Model):
    title = models.CharField(max_length=200)  # Заголовок
    intro = models.TextField()  # Вводная часть новости
    status_choices = [
        ('good', 'Хорошая'),
        ('needs_review', 'Требует проверки'),
        ('bad', 'Плохая'),
    ]
    status = models.CharField(max_length=15, choices=status_choices, default='needs_review')  # Статус новости
    source_link = models.URLField()  # Ссылка на источник
    ai_status = models.CharField(max_length=15, choices=status_choices, blank=True, null=True)  # Статус ИИ

    def __str__(self):
        return self.title

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'


class ScheduledTask(models.Model):
    name = models.CharField(max_length=255)
    next_run_time = models.DateTimeField()
    interval_minutes = models.IntegerField()

    def __str__(self):
        return self.name

NewsApp/forms.py
# newsapp/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import News, Profile, Bank, Manager
import requests

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'intro', 'status', 'source_link']

    def save(self, commit=True):
        news_instance = super().save(commit=False)
        ai_status = self.get_ai_status(news_instance.intro)
        news_instance.ai_status = ai_status
        if commit:
            news_instance.save()
        return news_instance

    def get_ai_status(self, intro):
        url = "https://api.textcortex.com/v1/texts/completions"
        headers = {
            "Authorization": "Bearer gAAAAABmmVXaqnu4t9AkjgGKghEOZQMInu5iaA6vqioGy9nWZwu_oIQHbreGPIP-GvyHmmPAQHA5Xom_ox8Wgu8jxTcRLqKjagZ9nL_AfQzdV6BAh5HT3DEzw0I6nF0P2Y4-SgjWpCji",
            "Content-Type": "application/json"
        }
        data = {
            "formality": "default",
            "max_tokens": 2048,
            "model": "claude-3-haiku",
            "n": 1,
            "source_lang": "ru",
            "target_lang": "ru",
            "temperature": None,
            "text": f"Определите тон новости, это плохая или хорошая новость? Если хорошая то возвращай ответ good если плохая новость то возвращай ответ bad. Возвращаешь только good или bad. {intro}"
        }
        response = requests.post(url, json=data, headers=headers)
        if response.status_code == 200:
            ai_response = response.json()
            ai_content = ai_response['data']['outputs'][0]['text'].strip().lower()
            if ai_content in ['good', 'bad']:
                return ai_content
        return 'needs_review'

class ManagerRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.is_staff = True  # Сделать пользователя менеджером
        if commit:
            user.save()
            Manager.objects.create(user=user)
        return user


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']

class SearchForm(forms.Form):
    query = forms.CharField(max_length=255, required=False, label='Поиск')


class NewsStatusForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['status']

class BankCreationForm(forms.ModelForm):
    manager = forms.ModelChoiceField(
        queryset=Manager.objects.all(),
        required=False,
        label='Manager',
        widget=forms.Select()
    )

    class Meta:
        model = Bank
        fields = ['name', 'ceo', 'manager']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['manager'].queryset = Manager.objects.all().select_related('user')
        self.fields['manager'].label_from_instance = lambda obj: f"{obj.user.last_name} {obj.user.first_name}"


class BankManagerForm(forms.ModelForm):
    manager = forms.ModelChoiceField(
        queryset=Manager.objects.all(),
        required=False,
        label='Manager',
        widget=forms.Select()
    )

    class Meta:
        model = Bank
        fields = ['manager']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['manager'].queryset = Manager.objects.all().select_related('user')
        self.fields['manager'].label_from_instance = lambda obj: f"{obj.user.last_name} {obj.user.first_name}"


class ManageBanksForm(forms.ModelForm):
    banks = forms.ModelMultipleChoiceField(
        queryset=Bank.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Banks"
    )

    class Meta:
        model = Manager
        fields = ['banks']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['banks'].label_from_instance = lambda obj: obj.name

NewsApp/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .models import News, Profile, Bank, Manager
from .forms import NewsForm, ManagerRegistrationForm, UserEditForm, ProfileEditForm, SearchForm, BankManagerForm, \
    BankCreationForm, ManageBanksForm


@login_required
def home(request):
    news_list = News.objects.all()
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        query = search_form.cleaned_data.get('query')
        if query:
            news_list = news_list.filter(title__icontains=query)

    return render(request, 'newsapp/home.html', {'news_list': news_list, 'search_form': search_form})


@login_required
def account(request):
    # Ensure profile exists
    if not hasattr(request.user, 'profile'):
        Profile.objects.create(user=request.user)

    # Ensure manager profile exists
    if not hasattr(request.user, 'manager'):
        Manager.objects.create(user=request.user)

    manager = request.user.manager

    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(request.POST, request.FILES, instance=request.user.profile)
        banks_form = ManageBanksForm(request.POST, instance=manager)
        if user_form.is_valid() and profile_form.is_valid() and banks_form.is_valid():
            user_form.save()
            profile_form.save()
            banks_form.save()
            return redirect('account')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        banks_form = ManageBanksForm(instance=manager)

    return render(request, 'newsapp/account.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'banks_form': banks_form,
        'manager': manager,
    })

@login_required
def analytics(request):
    return render(request, 'newsapp/analytics.html')


@login_required
def add_news(request):
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = NewsForm()
    return render(request, 'newsapp/add_news.html', {'form': form})

@login_required
def add_manager(request):
    if request.method == 'POST':
        form = ManagerRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lists')
    else:
        form = ManagerRegistrationForm()
    return render(request, 'newsapp/add_manager.html', {'form': form})

@login_required
@csrf_exempt
def change_news_status(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            news_id = data.get('news_id')
            status = data.get('status')
            news = News.objects.get(id=news_id)
            news.status = status
            news.save()
            return JsonResponse({'success': True})
        except News.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Новость не найдена.'}, status=404)
        except json.JSONDecodeError:
            return JsonResponse({'success': False, 'message': 'Ошибка декодирования JSON.'}, status=400)
    return JsonResponse({'success': False, 'message': 'Неправильный метод запроса.'}, status=400)

def lists(request):
    banks = Bank.objects.all()
    return render(request, 'newsapp/lists.html', {'banks': banks})

def update_bank_manager(request, bank_id):
    bank = get_object_or_404(Bank, id=bank_id)
    if request.method == 'POST':
        form = BankManagerForm(request.POST, instance=bank)
        if form.is_valid():
            form.save()
            return redirect('lists')
    else:
        form = BankManagerForm(instance=bank)
    return render(request, 'newsapp/update_bank_manager.html', {'form': form, 'bank': bank})

def create_bank(request):
    if request.method == 'POST':
        form = BankCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bank_list')
    else:
        form = BankCreationForm()
    return render(request, 'newsapp/create_bank.html', {'form': form})


@login_required
def remove_bank(request, bank_id):
    manager = request.user.manager
    bank = get_object_or_404(Bank, id=bank_id)
    manager.banks_managed.remove(bank)
    return redirect('account')

NewsApp/templates/newsapp/account.html
{% extends "newsapp/base.html" %}

{% block title %}Мой аккаунт{% endblock %}

{% block content %}
<div class="profile">
    <h2 class="profile__title">
        Edit profile
    </h2>
    <div class="profile__item">
        {% if user.profile.photo %}
            <img src="{{ user.profile.photo.url }}" alt="" width="64px" height="64px">
        {% else %}
            <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
        {% endif %}
        <div class="profile__info">
            <h4>{{ user.username }}</h4>
            <p>Change profile photo</p>
        </div>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="profile__input">
            <h4>Username</h4>
            {{ user_form.username }}
        </div>
        <div class="profile__input">
            <h4>Email</h4>
            {{ user_form.email }}
        </div>
        <div class="profile__input">
            <h4>First name</h4>
            {{ user_form.first_name }}
        </div>
        <div class="profile__input">
            <h4>Last name</h4>
            {{ user_form.last_name }}
        </div>
        <div class="profile__input">
            <h4>Profile photo</h4>
            {{ profile_form.photo }}
        </div>
        <div class="profile__buttons">
            <button class="profile__button" type="submit">Save changes</button>
        </div>
    </form>
</div>
{% endblock %}

NewsApp/templates/newsapp/add_bank.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

NewsApp/templates/newsapp/add_manager.html
{% extends 'newsapp/base.html' %}

{% block title %}Добавить менеджера{% endblock %}

{% block content %}
<div class="content">
    <h2>Добавить менеджера</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="content__button">Сохранить</button>
    </form>
</div>
{% endblock %}

NewsApp/templates/newsapp/add_news.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить новость</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'newsapp/css/add_news.css' %}">
</head>
<body>
    <aside>
        <nav>
            <ul>
                <header>
                    <h1>Supervision system</h1>
                </header>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="#">Lists</a></li>
                <li><a href="#">Analytics</a></li>
                <li><a href="{% url 'account' %}">Account</a></li>
            </ul>
        </nav>
    </aside>
    <main>
        <section class="add-news">
            <h2>Добавить новость</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Добавить новость</button>
            </form>
        </section>
    </main>
</body>
</html>

NewsApp/templates/newsapp/analytics.html
{% extends 'newsapp/base.html' %}

{% block title %}Аналитика{% endblock %}

{% block content %}
<div class="stats">
    <div class="stats__top">
        <div class="stats__top-item">
            <h4>Title</h4>
            <h2 class="stats__price">$45,343.89</h2>
            <h4>+20% month over month</h4>
        </div>
        <div class="stats__top-item">
            <h4>Title</h4>
            <h2 class="stats__price">$45,343.89</h2>
            <h4>+20% month over month</h4>
        </div>
        <div class="stats__top-item">
            <h4>Title</h4>
            <h2 class="stats__price">$45,343.89</h2>
            <h4>+20% month over month</h4>
        </div>
    </div>

    <div class="stat__component">
        <img src="https://placehold.jp/575x370.png" alt="">
        <div class="stat__comp-users">
            <h4>Title</h4>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
        </div>
    </div>
    <div class="stat__component">
        <img src="https://placehold.jp/575x370.png" alt="">
        <div class="stat__comp-users">
            <h4>Title</h4>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
            <div class="profile__item">
                <img src="https://placehold.jp/64x64.png" alt="" width="64px" height="64px">
                <div class="profile__info">
                    <h4>Manager 1</h4>
                    <p>Change profile photo</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

NewsApp/templates/newsapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'newsapp/css/style.css' %}">
    <title>{% block title %}Document{% endblock %}</title>
</head>
<body>
    <section class="home">
        <aside class="home__aside">
            <ul class="list">
                <a href="#" class="list__title">Supervision System</a>
                <li class="list__item"><a href="{% url 'home' %}">Home</a></li>
                <li class="list__item"><a href="{% url 'lists' %}">Lists</a></li>
                <li class="list__item"><a href="{% url 'analytics' %}">Analytics</a></li>
                <li class="list__item"><a href="{% url 'account' %}">Account</a></li>
            </ul>
        </aside>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </section>
    <script src="https://kit.fontawesome.com/962c6acd8f.js" crossorigin="anonymous"></script>
</body>
</html>

NewsApp/templates/newsapp/create_bank.html
{% extends 'newsapp/base.html' %}

{% block title %}Create Bank{% endblock %}

{% block content %}
    <h2>Create New Bank</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Create</button>
    </form>
{% endblock %}

NewsApp/templates/newsapp/home.html
{% extends 'newsapp/base.html' %}

{% block title %}Домашняя страница{% endblock %}

{% block content %}
<div class="content__top">
    <div class="content__top-right">
        <form method="get">
            <input type="text" class="input" name="query" placeholder="Search" value="{{ request.GET.query }}">
            <button type="submit" class="content__button"><i class="fa-solid fa-magnifying-glass"></i> Поиск</button>
        </form>
    </div>
    <div class="content__top-left">
        <button class="content__button--small content__button--small-active"><i class="fa-regular fa-calendar"></i></button>
        <button class="content__button--small"><i class="fa-solid fa-table-cells-large"></i></button>
        <button class="content__button--small"><i class="fa-solid fa-list"></i></button>
    </div>
</div>
<div class="content__inner">
    {% for news in news_list %}
    <div class="content__item" data-news-id="{{ news.id }}">
        <div class="content__uptitle">
            <p>Источник: <a href="{{ news.source_link }}">{{ news.source_link }}</a></p>
        </div>
        <div class="content__main-text">
            <h2>{{ news.title }}</h2>
            <p>{{ news.intro }}</p>
        </div>
        <div class="content__subtitle">
            <p>Статус:
                <select class="news-status-select" data-news-id="{{ news.id }}">
                    <option value="needs_review" {% if news.status == 'needs_review' %}selected{% endif %}>Требует проверки</option>
                    <option value="good" {% if news.status == 'good' %}selected{% endif %}>Хорошая</option>
                    <option value="bad" {% if news.status == 'bad' %}selected{% endif %}>Плохая</option>
                </select>
            </p>
            <p>Тональность ИИ: <span>{{ news.get_ai_status_display }}</span></p>
        </div>
    </div>
    {% empty %}
    <p>Новости не найдены.</p>
    {% endfor %}
</div>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const selects = document.querySelectorAll('.news-status-select');

    selects.forEach(select => {
        select.addEventListener('change', function () {
            const newsId = this.getAttribute('data-news-id');
            const status = this.value;

            fetch('{% url "change_news_status" %}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({
                    news_id: newsId,
                    status: status
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert('Статус успешно обновлен.');
                } else {
                    alert('Ошибка при обновлении статуса.');
                }
            })
            .catch(error => {
                console.error('Error:', error);
                alert('Произошла ошибка при обновлении статуса.');
            });
        });
    });
});
</script>
{% endblock %}

NewsApp/templates/newsapp/lists.html
{% extends 'newsapp/base.html' %}

{% block title %}Списки{% endblock %}

{% block content %}
    <div class="content__top">
        <div class="content__top-right">
            <input type="text" class="input" placeholder="Search">
            <button class="content__button"><i class="fa-solid fa-magnifying-glass"></i> Filter</button>
        </div>
        <div class="content__top-left">
            <button class="content__button--small content__button--small-active"><i class="fa-regular fa-calendar"></i></button>
            <button class="content__button--small"><i class="fa-solid fa-table-cells-large"></i></button>
            <button class="content__button--small"><i class="fa-solid fa-list"></i></button>
        </div>
    </div>
    <div class="table">
        <div class="table__top">
            <div class="table-left">
                <p>Num</p>
                <h3>Company</h3>
            </div>
            <div class="table-right">
                <h3>Manager</h3>
                <h3>CEO</h3>
            </div>
        </div>
        {% for bank in banks %}
        <div class="table__item">
            <div class="table__item-left">
                <p class="table__item-left-num">{{ forloop.counter }}</p>
                <h4 class="table__item-left-name">{{ bank.name }}</h4>
            </div>
            <div class="table__item-right">
                {% if bank.manager %}
                    <p>{{ bank.manager.user.last_name }} {{ bank.manager.user.first_name }}</p>
                {% else %}
                    <p>No Manager</p>
                {% endif %}
                <p>{{ bank.ceo }}</p>
                <a href="{% url 'update_bank_manager' bank.id %}" class="button">Edit Manager</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if user.is_superuser %}
    <div class="content__bottom">
        <a href="{% url 'add_manager' %}" class="content__button content__button--black">Добавить менеджера</a>
        <a href="{% url 'create_bank' %}" class="content__button content__button--black">Создать банк</a>
    </div>
    {% endif %}
{% endblock %}

NewsApp/templates/newsapp/update_bank_manager.html
{% extends 'newsapp/base.html' %}

{% block title %}Update Bank Manager{% endblock %}

{% block content %}
    <h2>Update Manager for {{ bank.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Save</button>
    </form>
{% endblock %}